project:
  type: website

website:
  title: "Workshop"
  page-footer: "Created with [Quarto](https://quarto.org/)"
  repo-url: https://github.com/derisiswara/workshop
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true


